alertmanager:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: false
server:
  persistentVolume:
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 100Gi
extraScrapeConfigs: |
  - job_name: opencost
    honor_labels: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
    - names:
      - opencost.opencost
      type: 'A'
      port: 9003
serverFiles:
  alerting_rules.yml:
    groups:
      - name: Instances
        rules:
          - alert: InstanceDown
            expr: up == 0
            for: 5m
            labels:
              severity: page
            annotations:
              description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
              summary: 'Instance {{ $labels.instance }} down'
  recording_rules.yml:
    groups:
      - name: Recording-rule-test
        rules:
        - record: namespace:cpu_requests:sum
          expr: sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)
        - record: namespace:cpu_limits:sum
          expr: sum(kube_pod_container_resource_limits_cpu_cores) by (namespace)
